### ISSUE TITLE
Move getArrayPair to separate library

### ISSUE THREAD

**Issue by Gr3it** [DeFi-Space-Pirates/DeFi-Space-Pirates#23]
After the split contract and dex merge move this function to a library

**Comment by HenricoW** [comment]
Hi. Is this still something you need done?

I see that getArrayPair is only defined and used in two contracts:
1. ERC1155Batch.sol and
2. AsteroidsSplitContract.sol

**Comment by Gr3it** [comment]
Yes, it is still to be done, you can do it.
Please, fork the repo, create a dedicated branch and then open a pull request.

**Comment by Gr3it** [comment]
Yes, it is still to be done, you can do it.
Please, fork the repo, create a dedicated branch and then open a pull request.
